// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDQs1PdWxB-Vrk3LYyExiaH_gu0kGvjAw',
    appId: '1:48836817905:web:5bc4e7b0f5d0f867768a50',
    messagingSenderId: '48836817905',
    projectId: 'caffeine-app-31861',
    authDomain: 'caffeine-app-31861.firebaseapp.com',
    storageBucket: 'caffeine-app-31861.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMYle8M6Ii0oNPclWn-RcRqu8K3JU0nc0',
    appId: '1:48836817905:android:7280fa6cf75d4c5e768a50',
    messagingSenderId: '48836817905',
    projectId: 'caffeine-app-31861',
    storageBucket: 'caffeine-app-31861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3picrwBHovb_gHNYWP9BgMaML9syzkFE',
    appId: '1:48836817905:ios:8871a5fa70703e79768a50',
    messagingSenderId: '48836817905',
    projectId: 'caffeine-app-31861',
    storageBucket: 'caffeine-app-31861.firebasestorage.app',
    iosBundleId: 'com.example.caffeineTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3picrwBHovb_gHNYWP9BgMaML9syzkFE',
    appId: '1:48836817905:ios:8871a5fa70703e79768a50',
    messagingSenderId: '48836817905',
    projectId: 'caffeine-app-31861',
    storageBucket: 'caffeine-app-31861.firebasestorage.app',
    iosBundleId: 'com.example.caffeineTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDQs1PdWxB-Vrk3LYyExiaH_gu0kGvjAw',
    appId: '1:48836817905:web:e4403140eb7a9dde768a50',
    messagingSenderId: '48836817905',
    projectId: 'caffeine-app-31861',
    authDomain: 'caffeine-app-31861.firebaseapp.com',
    storageBucket: 'caffeine-app-31861.firebasestorage.app',
  );
}
